# Generated by Django 4.2.1 on 2023-10-03 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Category",
            new_name="caseategory",
        ),
    ]
