# Generated by Django 4.2.1 on 2023-10-03 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0002_rename_category_post_caseategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="caseategory",
            new_name="category",
        ),
    ]
